env:
  browser: true
  es2021: true
extends: standard-with-typescript
plugins:
  - "@typescript-eslint/eslint-plugin"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: 
    - tsconfig.json
ignorePatterns:
    - jest.config.js
rules:
  "@typescript-eslint/semi": ["error", "always"]
  "@typescript-eslint/no-extra-semi": "error"
